# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3401ddca101fc92a6d32b14dad2fcce89042733f9896f719f2dca0e6fd6203f56fcce8521f7f3afccfaffd2c44f84ed07685461022faac77aec2a356962ea0c2

test:
  secret_key_base: c23022855d43e1c1c5588087caf988ff7e3303df2c84c307f443c64df3955d55a03e9ac856813102c749e036fd760a445321479bc1cadd90957a493d7f0b342e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
