# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a6e15eca7cb917b2614857a5ff45120576aed936d2f484e1f359ede18b3d7028d2eaf7860069bde165ff80ebe1b98ec62e5b3fc37bbaeb027b222f9ad7ec1b

test:
  secret_key_base: a5c06d58095a8ef2a04cd3a502c3bfc4f45a0901e516943ba160b4612bab2e220b079b37aef94973e24eb07c98555f301126a98fa51119bba0fa93d392aeeec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
